### PR TITLE
closes #28 Added eslinter and removed linting errors

### LINKED ISSUE #28: Add standard linting
- [ ] Add [vue standard config](https://www.npmjs.com/package/@vue/eslint-config-standard) for eslint
- [ ] Lint the project and fix all the errors

This makes it easier for collaborators, yay 🎐

### PR DESCRIPTION
**Pull request by svenkirchner**

### CODE REVIEW

**Comment by Fohlen** [comment]
Hey @hilsmann 
First of all thanks for you PR ✨ 
Apparently there's still some work to do according to Travis, namely:

- add `process`, `require` and `module` to globals
- allow `console` statements (or use `// eslint-disable-line no-console`)

Could you do this? I'll merge the PR asap once Travis is green ✅ 
Greetings from rainy Tuebingen 🌧

**Review by Fohlen — CHANGES_REQUESTED** [review]
So far so good, we only need to make Travis work as well.

**Comment by svenkirchner** [comment]
> 
> 
> Hey @hilsmann
> First of all thanks for you PR ✨
> Apparently there's still some work to do according to Travis, namely:
> 
>     * add `process`, `require` and `module` to globals
> 
>     * allow `console` statements (or use `// eslint-disable-line no-console`)
> 
> 
> Could you do this? I'll merge the PR asap once Travis is green ✅
> Greetings from rainy Tuebingen 🌧

Hello @Fohlen 
I removed all linting errors by adding eslint rules. I hope it is okay. I think this solution is a bit better than to make those functions call into a global variable or global function. 💻 
Travis is now ready to go. ✔️  
Greetings

**Comment by Fohlen** [comment]
Hey @hilsmann 
This is amazing, thanks for the PR!

As you like, consider adding yourself to the [CONTRIBUTORS](https://github.com/eventzimmer/schema/blob/master/CONTRIBUTORS.md) list.
Happy Hacktober!

**Pull request merged**
